apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp
spec:
  source:
    path: test
    repoURL: https://github.com/schmhj/argocd-app-config.git
    targetRevision: HEAD

  destination:
    namespace: testapp
    server: https://kubernetes.default.svc
  project: testapp

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      